# Pre-commit configuration file

repos:
  - repo: local
    hooks:
      - id: cz-check
        name: Commitizen check
        entry: cz check
        language: system
        stages: [commit-msg]
      - id: commitlint
        name: Commitlint 52-char header
        entry: npx --yes commitlint --edit $1
        language: system
        stages: [commit-msg]

