[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "econexyz"
version = "0.0.0"
description = "EcoNexyz example project"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "EcoNexyz"}]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-bdd",
    "hypothesis",
    "pytest-cov",
]
dev = [
    "ruff",
    "nox",
    "ty",
]

[tool.ruff]
select = ["E", "F", "UP", "I"]
line-length = 120

[tool.ty]
strict = true
python_version = "3.12"
packages = ["econexyz"]

