openapi: 3.1.0
info:
  title: EcoNexyz API
  version: 0.0.0
paths:
  /ping:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                  - ok
                example:
                  ok: true
