name: commit-style

on:
  pull_request:
    branches: [main]

jobs:
  commit-style:
    name: commit-style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install commitizen
        run: pip install commitizen
      - name: Commitizen check
        run: |
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
      - name: Commitlint (header ≤52 chars etc.)
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.cjs
