name: Commit style

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install commitizen
        run: pip install commitizen
      - name: Commitizen check
        run: |
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
      - name: Commitlint (header ≤52 chars etc.)
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.cjs
