name: docs

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bootstrap.sh
      - run: nox -s docs
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: docs/_build/html
          publish_branch: gh-pages

